version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro #映射nginx的配置文件到容器里
      - ./logs/:/var/log/nginx/
      - ./www/:/var/share/nginx/html/:ro
    networks:
      - net-nginx
  mysql:
    image: mysql:5.7.23
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql/:/var/lib/mysql/:rw
    environment:
      MYSQL_ROOT_PASSWORD: "Sangoes@15s09"
    networks:
      - net-mysql
  redis:
    image: redis:4.0
    restart: always
    networks:
      - net-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
  rabbit:
    image: rabbitmq:management
    hostname: rabbit
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=sangoes
      - RABBITMQ_DEFAULT_PASS=Sangoes@15s09
    networks:
      - net-rabbitmq
networks:
  ? net-nginx
  ? net-rabbitmq
  ? net-redis
  ? net-mysql
