version: "3"
services:
  nginx:
    image: nginx:1.15.5
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/usr/share/nginx/html:ro
      - ./logs:/var/log/nginx
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/conf.d:/etc/nginx/conf.d
    networks:
      - net-sangoes
  mysql:
    image: mysql:5.7.23
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql/:/var/lib/mysql/:rw
    environment:
      MYSQL_USER: sangoes
      MYSQL_PASSWORD: "Sangoes123456"
      MYSQL_ROOT_PASSWORD: "Sangoes123456"
    networks:
      - net-sangoes
  redis:
    image: redis:4.0.11
    restart: always
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - net-sangoes
  rabbit:
    image: rabbitmq:management
    hostname: rabbit
    restart: always
    container_name: rabbit
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=sangoes
      - RABBITMQ_DEFAULT_PASS=Sangoes123456
    networks:
      - net-sangoes
  jenkins:
    build: ./jenkins
    image: sangoes/jenkins
    restart: always
    container_name: jenkins
    ports:
      - "8181:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/jenkins/bin:/bin/docker
      - /docker/jenkins/data:/var/jenkins_home
    networks:
      - net-sangoes
#  fastdfs:
#    build:
#      context: ./
#      dockerfile: dockerfile/fdfs/DockerFile
#    image: jerrychir/fastdfs:5.11
#    # 该容器是否需要开机启动+自动重启。若需要，则取消注释。
#    restart: always
#    container_name: fastdfs
#    environment:
#    # nginx服务端口
#    - WEB_PORT=8888
#    # docker所在主机的IP地址
#    - IP=127.0.0.1
#    volumes:
#    # 将本地目录映射到docker容器内的fastdfs数据存储目录，将fastdfs文件存储到主机上，以免每次重建docker容器，之前存储的文件就丢失了。
#    - ./fdfs:/var/local/fdfs
#    # 使docker具有root权限以读写主机上的目录
#    privileged: true
#    # 网络模式为host，即直接使用主机的网络接口
#    network_mode: "host"
networks:
  net-sangoes:
    external: true
