version: "3"
services:
  nginx:
    image: nginx:1.15.5
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/usr/share/nginx/html:ro
      - ./logs:/var/log/nginx
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/conf.d:/etc/nginx/conf.d
    networks:
      - net-nginx
#
#  fastdfs:
#    build:
#      context: ./
#      dockerfile: dockerfile/fdfs/DockerFile
#    image: jerrychir/fastdfs:5.11
#    # 该容器是否需要开机启动+自动重启。若需要，则取消注释。
#    restart: always
#    container_name: fastdfs
#    environment:
#    # nginx服务端口
#    - WEB_PORT=8888
#    # docker所在主机的IP地址
#    - IP=47.88.229.205
#    volumes:
#    # 将本地目录映射到docker容器内的fastdfs数据存储目录，将fastdfs文件存储到主机上，以免每次重建docker容器，之前存储的文件就丢失了。
#    - ./fdfs:/var/local/fdfs
#    # 使docker具有root权限以读写主机上的目录
#    privileged: true
#    # 网络模式为host，即直接使用主机的网络接口
#    network_mode: "host"
networks:
  ? net-nginx
  # net-rabbitmq:
  # net-redis:
  # net-mysql:
