version: "3.0"
services:
  zentao:
    build: .
    image: sangoes/zentao
    # 该容器是否需要开机启动+自动重启。若需要，则取消注释。
    restart: always
    container_name: zentao
    environment:
      - MYSQL_ROOT_PASSWORD:123456
    ports:
      - "8888:80"
    volumes:
      - /docker/data/www:/app/zentaopms
      - /docker/data/data:/var/lib/mysql
    # 使docker具有root权限以读写主机上的目录
    privileged: true
    # 网络模式为host，即直接使用主机的网络接口
    network_mode: "host"
