version: "3"
services:
  nginx:
    # build: .
    image: nginx:1.15.5
    # 该容器是否需要开机启动+自动重启。若需要，则取消注释。
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /docker/nginx/www:/usr/share/nginx/html:ro
      - /docker/nginx/logs:/var/log/nginx
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/conf.d:/etc/nginx/conf.d
    # 使docker具有root权限以读写主机上的目录
    privileged: true
    # 网络模式为host，即直接使用主机的网络接口
    network_mode: "host"
